<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260222144734 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE "user" (id SERIAL NOT NULL, email VARCHAR(180) NOT NULL, username VARCHAR(255) NOT NULL, roles JSON NOT NULL, password VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649E7927C74 ON "user" (email)');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_8D93D649F85E0677 ON "user" (username)');
        $this->addSql('COMMENT ON COLUMN "user".created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN "user".updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE being (id SERIAL NOT NULL, game_id INT DEFAULT NULL, user_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, last_name VARCHAR(255) DEFAULT NULL, level INT NOT NULL, current_health_points INT NOT NULL, max_health_points INT NOT NULL, current_mana_points INT NOT NULL, max_mana_points INT NOT NULL, current_action_points INT NOT NULL, max_action_points INT NOT NULL, current_exhaust_points INT NOT NULL, max_exhaust_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, type VARCHAR(255) NOT NULL, token VARCHAR(255) DEFAULT NULL, is_boss BOOLEAN DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_4686967CE48FD905 ON being (game_id)');
        $this->addSql('CREATE INDEX IDX_4686967CA76ED395 ON being (user_id)');
        $this->addSql('COMMENT ON COLUMN being.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN being.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE being_spells (being_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(being_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_11CAE50A186A5FCB ON being_spells (being_id)');
        $this->addSql('CREATE INDEX IDX_11CAE50A479EC90D ON being_spells (spell_id)');
        $this->addSql('CREATE TABLE being_skills (being_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(being_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_4C2CFC21186A5FCB ON being_skills (being_id)');
        $this->addSql('CREATE INDEX IDX_4C2CFC215585C142 ON being_skills (skill_id)');
        $this->addSql('CREATE TABLE being_items (being_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY(being_id, item_id))');
        $this->addSql('CREATE INDEX IDX_F5A5024E186A5FCB ON being_items (being_id)');
        $this->addSql('CREATE INDEX IDX_F5A5024E126F525E ON being_items (item_id)');
        $this->addSql('CREATE TABLE playable_characters_kind (being_id INT NOT NULL, kind_id INT NOT NULL, PRIMARY KEY(being_id, kind_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_94787C3C186A5FCB ON playable_characters_kind (being_id)');
        $this->addSql('CREATE INDEX IDX_94787C3C30602CA9 ON playable_characters_kind (kind_id)');
        $this->addSql('CREATE TABLE playable_characters_character_class (being_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY(being_id, character_class_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E0683910186A5FCB ON playable_characters_character_class (being_id)');
        $this->addSql('CREATE INDEX IDX_E0683910B201E281 ON playable_characters_character_class (character_class_id)');
        $this->addSql('CREATE TABLE monsters_specie (being_id INT NOT NULL, specie_id INT NOT NULL, PRIMARY KEY(being_id, specie_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FFA328D7186A5FCB ON monsters_specie (being_id)');
        $this->addSql('CREATE INDEX IDX_FFA328D7D5436AB7 ON monsters_specie (specie_id)');
        $this->addSql('CREATE TABLE non_playable_characters_kind (being_id INT NOT NULL, kind_id INT NOT NULL, PRIMARY KEY(being_id, kind_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CA9E5A17186A5FCB ON non_playable_characters_kind (being_id)');
        $this->addSql('CREATE INDEX IDX_CA9E5A1730602CA9 ON non_playable_characters_kind (kind_id)');
        $this->addSql('CREATE TABLE non_playable_characters_character_class (being_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY(being_id, character_class_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_E165B81186A5FCB ON non_playable_characters_character_class (being_id)');
        $this->addSql('CREATE INDEX IDX_E165B81B201E281 ON non_playable_characters_character_class (character_class_id)');
        $this->addSql('CREATE TABLE being_talent (being_id INT NOT NULL, talent_id INT NOT NULL, value INT NOT NULL, PRIMARY KEY(being_id, talent_id))');
        $this->addSql('CREATE INDEX IDX_8FC4E8A4186A5FCB ON being_talent (being_id)');
        $this->addSql('CREATE INDEX IDX_8FC4E8A418777CEF ON being_talent (talent_id)');
        $this->addSql('CREATE TABLE character_class (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1388FEFDDE12AB56 ON character_class (created_by)');
        $this->addSql('COMMENT ON COLUMN character_class.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN character_class.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE character_template (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, min_health_points INT NOT NULL, max_health_points INT NOT NULL, min_mana_points INT NOT NULL, max_mana_points INT NOT NULL, min_action_points INT NOT NULL, max_action_points INT NOT NULL, min_exhaust_points INT NOT NULL, max_exhaust_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_CF61F612DE12AB56 ON character_template (created_by)');
        $this->addSql('COMMENT ON COLUMN character_template.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN character_template.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE character_templates_kind (character_template_id INT NOT NULL, kind_id INT NOT NULL, PRIMARY KEY(character_template_id, kind_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_CB4A2651B0A514 ON character_templates_kind (character_template_id)');
        $this->addSql('CREATE INDEX IDX_CB4A26530602CA9 ON character_templates_kind (kind_id)');
        $this->addSql('CREATE TABLE character_templates_character_class (character_template_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY(character_template_id, character_class_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_D53A531B0A514 ON character_templates_character_class (character_template_id)');
        $this->addSql('CREATE INDEX IDX_D53A53B201E281 ON character_templates_character_class (character_class_id)');
        $this->addSql('CREATE TABLE character_templates_spells (character_template_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(character_template_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_3AA8E4FC1B0A514 ON character_templates_spells (character_template_id)');
        $this->addSql('CREATE INDEX IDX_3AA8E4FC479EC90D ON character_templates_spells (spell_id)');
        $this->addSql('CREATE TABLE character_templates_skills (character_template_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(character_template_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_674EFDD71B0A514 ON character_templates_skills (character_template_id)');
        $this->addSql('CREATE INDEX IDX_674EFDD75585C142 ON character_templates_skills (skill_id)');
        $this->addSql('CREATE TABLE character_templates_items (character_template_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY(character_template_id, item_id))');
        $this->addSql('CREATE INDEX IDX_23FE66F41B0A514 ON character_templates_items (character_template_id)');
        $this->addSql('CREATE INDEX IDX_23FE66F4126F525E ON character_templates_items (item_id)');
        $this->addSql('CREATE TABLE equipment (id SERIAL NOT NULL, game_id INT DEFAULT NULL, being_id INT DEFAULT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, value INT DEFAULT NULL, current_durability_points INT NOT NULL, max_durability_points INT NOT NULL, description TEXT NOT NULL, is_owned BOOLEAN DEFAULT false NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D338D583E48FD905 ON equipment (game_id)');
        $this->addSql('CREATE INDEX IDX_D338D583186A5FCB ON equipment (being_id)');
        $this->addSql('COMMENT ON COLUMN equipment.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equipment.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE equipments_skills (equipment_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(equipment_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_F4A04905517FE9FE ON equipments_skills (equipment_id)');
        $this->addSql('CREATE INDEX IDX_F4A049055585C142 ON equipments_skills (skill_id)');
        $this->addSql('CREATE TABLE equipments_spells (equipment_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(equipment_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_A946502E517FE9FE ON equipments_spells (equipment_id)');
        $this->addSql('CREATE INDEX IDX_A946502E479EC90D ON equipments_spells (spell_id)');
        $this->addSql('CREATE TABLE equipment_template (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, category VARCHAR(255) NOT NULL, value INT DEFAULT NULL, min_durability INT NOT NULL, max_durability INT NOT NULL, weight INT NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A7A39BA5DE12AB56 ON equipment_template (created_by)');
        $this->addSql('COMMENT ON COLUMN equipment_template.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN equipment_template.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE equipment_templates_skills (equipment_template_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(equipment_template_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_A47E8C7F6498FB9F ON equipment_templates_skills (equipment_template_id)');
        $this->addSql('CREATE INDEX IDX_A47E8C7F5585C142 ON equipment_templates_skills (skill_id)');
        $this->addSql('CREATE TABLE equipment_templates_spells (equipment_template_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(equipment_template_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_F99895546498FB9F ON equipment_templates_spells (equipment_template_id)');
        $this->addSql('CREATE INDEX IDX_F9989554479EC90D ON equipment_templates_spells (spell_id)');
        $this->addSql('CREATE TABLE game (id SERIAL NOT NULL, game_master INT DEFAULT NULL, name VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_232B318C503C0E1E ON game (game_master)');
        $this->addSql('COMMENT ON COLUMN game.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN game.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE item (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, value INT NOT NULL, weight INT NOT NULL, current_durability_points INT NOT NULL, max_durability_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_1F1B251EDE12AB56 ON item (created_by)');
        $this->addSql('COMMENT ON COLUMN item.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN item.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE kind (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_3BC4BCD9DE12AB56 ON kind (created_by)');
        $this->addSql('COMMENT ON COLUMN kind.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN kind.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE mastery (id SERIAL NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE TABLE monster_template (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, min_health_points INT NOT NULL, max_health_points INT NOT NULL, min_mana_points INT NOT NULL, max_mana_points INT NOT NULL, min_action_points INT NOT NULL, max_action_points INT NOT NULL, min_exhaust_points INT NOT NULL, max_exhaust_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_21A4530FDE12AB56 ON monster_template (created_by)');
        $this->addSql('COMMENT ON COLUMN monster_template.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN monster_template.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE monster_templates_specie (monster_template_id INT NOT NULL, specie_id INT NOT NULL, PRIMARY KEY(monster_template_id, specie_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_9CBBCC5F2D30EB4A ON monster_templates_specie (monster_template_id)');
        $this->addSql('CREATE INDEX IDX_9CBBCC5FD5436AB7 ON monster_templates_specie (specie_id)');
        $this->addSql('CREATE TABLE monster_templates_spells (monster_template_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(monster_template_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_1E44CA762D30EB4A ON monster_templates_spells (monster_template_id)');
        $this->addSql('CREATE INDEX IDX_1E44CA76479EC90D ON monster_templates_spells (spell_id)');
        $this->addSql('CREATE TABLE monster_templates_items (monster_templates_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY(monster_templates_id, item_id))');
        $this->addSql('CREATE INDEX IDX_7B734A0771552540 ON monster_templates_items (monster_templates_id)');
        $this->addSql('CREATE INDEX IDX_7B734A07126F525E ON monster_templates_items (item_id)');
        $this->addSql('CREATE TABLE monster_templates_skills (monster_template_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(monster_template_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_43A2D35D2D30EB4A ON monster_templates_skills (monster_template_id)');
        $this->addSql('CREATE INDEX IDX_43A2D35D5585C142 ON monster_templates_skills (skill_id)');
        $this->addSql('CREATE TABLE non_playable_character_template (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, min_health_points INT NOT NULL, max_health_points INT NOT NULL, min_mana_points INT NOT NULL, max_mana_points INT NOT NULL, min_action_points INT NOT NULL, max_action_points INT NOT NULL, min_exhaust_points INT NOT NULL, max_exhaust_points INT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_9F46D872DE12AB56 ON non_playable_character_template (created_by)');
        $this->addSql('COMMENT ON COLUMN non_playable_character_template.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN non_playable_character_template.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE non_playable_character_templates_kind (non_playable_character_template_id INT NOT NULL, kind_id INT NOT NULL, PRIMARY KEY(non_playable_character_template_id, kind_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2BE8856DE76AD223 ON non_playable_character_templates_kind (non_playable_character_template_id)');
        $this->addSql('CREATE INDEX IDX_2BE8856D30602CA9 ON non_playable_character_templates_kind (kind_id)');
        $this->addSql('CREATE TABLE non_playable_character_templates_character_class (non_playable_character_template_id INT NOT NULL, character_class_id INT NOT NULL, PRIMARY KEY(non_playable_character_template_id, character_class_id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_70421A92E76AD223 ON non_playable_character_templates_character_class (non_playable_character_template_id)');
        $this->addSql('CREATE INDEX IDX_70421A92B201E281 ON non_playable_character_templates_character_class (character_class_id)');
        $this->addSql('CREATE TABLE non_playable_character_templates_spells (non_playable_character_template_id INT NOT NULL, spell_id INT NOT NULL, PRIMARY KEY(non_playable_character_template_id, spell_id))');
        $this->addSql('CREATE INDEX IDX_577BFCC3E76AD223 ON non_playable_character_templates_spells (non_playable_character_template_id)');
        $this->addSql('CREATE INDEX IDX_577BFCC3479EC90D ON non_playable_character_templates_spells (spell_id)');
        $this->addSql('CREATE TABLE non_playable_character_templates_items (non_playable_character_template_id INT NOT NULL, item_id INT NOT NULL, PRIMARY KEY(non_playable_character_template_id, item_id))');
        $this->addSql('CREATE INDEX IDX_2D02B2E1E76AD223 ON non_playable_character_templates_items (non_playable_character_template_id)');
        $this->addSql('CREATE INDEX IDX_2D02B2E1126F525E ON non_playable_character_templates_items (item_id)');
        $this->addSql('CREATE TABLE non_playable_character_templates_skills (non_playable_character_template_id INT NOT NULL, skill_id INT NOT NULL, PRIMARY KEY(non_playable_character_template_id, skill_id))');
        $this->addSql('CREATE INDEX IDX_A9DE5E8E76AD223 ON non_playable_character_templates_skills (non_playable_character_template_id)');
        $this->addSql('CREATE INDEX IDX_A9DE5E85585C142 ON non_playable_character_templates_skills (skill_id)');
        $this->addSql('CREATE TABLE skill (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, exhaust_point_cost INT NOT NULL, action_point_cost INT NOT NULL, dice_value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_5E3DE477DE12AB56 ON skill (created_by)');
        $this->addSql('COMMENT ON COLUMN skill.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN skill.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE specie (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(100) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_A280972DE12AB56 ON specie (created_by)');
        $this->addSql('COMMENT ON COLUMN specie.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN specie.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE spell (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, mana_cost INT NOT NULL, action_point_cost INT NOT NULL, dice_value VARCHAR(255) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_D03FCD8DDE12AB56 ON spell (created_by)');
        $this->addSql('COMMENT ON COLUMN spell.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN spell.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE talent (id SERIAL NOT NULL, created_by INT DEFAULT NULL, is_ready BOOLEAN DEFAULT true NOT NULL, is_private BOOLEAN DEFAULT false NOT NULL, name VARCHAR(255) NOT NULL, description TEXT NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, note TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_16D902F5DE12AB56 ON talent (created_by)');
        $this->addSql('COMMENT ON COLUMN talent.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN talent.updated_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('CREATE TABLE talent_level (id SERIAL NOT NULL, talent_id INT NOT NULL, level INT NOT NULL, description TEXT NOT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_6CBAD29418777CEF ON talent_level (talent_id)');
        $this->addSql('CREATE TABLE messenger_messages (id BIGSERIAL NOT NULL, body TEXT NOT NULL, headers TEXT NOT NULL, queue_name VARCHAR(190) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, available_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, delivered_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, PRIMARY KEY(id))');
        $this->addSql('CREATE INDEX IDX_75EA56E0FB7336F0E3BD61CE16BA31DBBF396750 ON messenger_messages (queue_name, available_at, delivered_at, id)');
        $this->addSql('COMMENT ON COLUMN messenger_messages.created_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.available_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('COMMENT ON COLUMN messenger_messages.delivered_at IS \'(DC2Type:datetime_immutable)\'');
        $this->addSql('ALTER TABLE being ADD CONSTRAINT FK_4686967CE48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being ADD CONSTRAINT FK_4686967CA76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_spells ADD CONSTRAINT FK_11CAE50A186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_spells ADD CONSTRAINT FK_11CAE50A479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_skills ADD CONSTRAINT FK_4C2CFC21186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_skills ADD CONSTRAINT FK_4C2CFC215585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_items ADD CONSTRAINT FK_F5A5024E186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_items ADD CONSTRAINT FK_F5A5024E126F525E FOREIGN KEY (item_id) REFERENCES item (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playable_characters_kind ADD CONSTRAINT FK_94787C3C186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playable_characters_kind ADD CONSTRAINT FK_94787C3C30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playable_characters_character_class ADD CONSTRAINT FK_E0683910186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE playable_characters_character_class ADD CONSTRAINT FK_E0683910B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monsters_specie ADD CONSTRAINT FK_FFA328D7186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monsters_specie ADD CONSTRAINT FK_FFA328D7D5436AB7 FOREIGN KEY (specie_id) REFERENCES specie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_characters_kind ADD CONSTRAINT FK_CA9E5A17186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_characters_kind ADD CONSTRAINT FK_CA9E5A1730602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_characters_character_class ADD CONSTRAINT FK_E165B81186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_characters_character_class ADD CONSTRAINT FK_E165B81B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_talent ADD CONSTRAINT FK_8FC4E8A4186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE being_talent ADD CONSTRAINT FK_8FC4E8A418777CEF FOREIGN KEY (talent_id) REFERENCES talent (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_class ADD CONSTRAINT FK_1388FEFDDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_template ADD CONSTRAINT FK_CF61F612DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_kind ADD CONSTRAINT FK_CB4A2651B0A514 FOREIGN KEY (character_template_id) REFERENCES character_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_kind ADD CONSTRAINT FK_CB4A26530602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_character_class ADD CONSTRAINT FK_D53A531B0A514 FOREIGN KEY (character_template_id) REFERENCES character_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_character_class ADD CONSTRAINT FK_D53A53B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_spells ADD CONSTRAINT FK_3AA8E4FC1B0A514 FOREIGN KEY (character_template_id) REFERENCES character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_spells ADD CONSTRAINT FK_3AA8E4FC479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_skills ADD CONSTRAINT FK_674EFDD71B0A514 FOREIGN KEY (character_template_id) REFERENCES character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_skills ADD CONSTRAINT FK_674EFDD75585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_items ADD CONSTRAINT FK_23FE66F41B0A514 FOREIGN KEY (character_template_id) REFERENCES character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE character_templates_items ADD CONSTRAINT FK_23FE66F4126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583E48FD905 FOREIGN KEY (game_id) REFERENCES game (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment ADD CONSTRAINT FK_D338D583186A5FCB FOREIGN KEY (being_id) REFERENCES being (id) ON DELETE SET NULL NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipments_skills ADD CONSTRAINT FK_F4A04905517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipments_skills ADD CONSTRAINT FK_F4A049055585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipments_spells ADD CONSTRAINT FK_A946502E517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipments_spells ADD CONSTRAINT FK_A946502E479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_template ADD CONSTRAINT FK_A7A39BA5DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_templates_skills ADD CONSTRAINT FK_A47E8C7F6498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_templates_skills ADD CONSTRAINT FK_A47E8C7F5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_templates_spells ADD CONSTRAINT FK_F99895546498FB9F FOREIGN KEY (equipment_template_id) REFERENCES equipment_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE equipment_templates_spells ADD CONSTRAINT FK_F9989554479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE game ADD CONSTRAINT FK_232B318C503C0E1E FOREIGN KEY (game_master) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE item ADD CONSTRAINT FK_1F1B251EDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE kind ADD CONSTRAINT FK_3BC4BCD9DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_template ADD CONSTRAINT FK_21A4530FDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_specie ADD CONSTRAINT FK_9CBBCC5F2D30EB4A FOREIGN KEY (monster_template_id) REFERENCES monster_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_specie ADD CONSTRAINT FK_9CBBCC5FD5436AB7 FOREIGN KEY (specie_id) REFERENCES specie (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_spells ADD CONSTRAINT FK_1E44CA762D30EB4A FOREIGN KEY (monster_template_id) REFERENCES monster_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_spells ADD CONSTRAINT FK_1E44CA76479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_items ADD CONSTRAINT FK_7B734A0771552540 FOREIGN KEY (monster_templates_id) REFERENCES monster_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_items ADD CONSTRAINT FK_7B734A07126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_skills ADD CONSTRAINT FK_43A2D35D2D30EB4A FOREIGN KEY (monster_template_id) REFERENCES monster_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE monster_templates_skills ADD CONSTRAINT FK_43A2D35D5585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_template ADD CONSTRAINT FK_9F46D872DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_kind ADD CONSTRAINT FK_2BE8856DE76AD223 FOREIGN KEY (non_playable_character_template_id) REFERENCES non_playable_character_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_kind ADD CONSTRAINT FK_2BE8856D30602CA9 FOREIGN KEY (kind_id) REFERENCES kind (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_character_class ADD CONSTRAINT FK_70421A92E76AD223 FOREIGN KEY (non_playable_character_template_id) REFERENCES non_playable_character_template (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_character_class ADD CONSTRAINT FK_70421A92B201E281 FOREIGN KEY (character_class_id) REFERENCES character_class (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_spells ADD CONSTRAINT FK_577BFCC3E76AD223 FOREIGN KEY (non_playable_character_template_id) REFERENCES non_playable_character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_spells ADD CONSTRAINT FK_577BFCC3479EC90D FOREIGN KEY (spell_id) REFERENCES spell (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_items ADD CONSTRAINT FK_2D02B2E1E76AD223 FOREIGN KEY (non_playable_character_template_id) REFERENCES non_playable_character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_items ADD CONSTRAINT FK_2D02B2E1126F525E FOREIGN KEY (item_id) REFERENCES item (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_skills ADD CONSTRAINT FK_A9DE5E8E76AD223 FOREIGN KEY (non_playable_character_template_id) REFERENCES non_playable_character_template (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE non_playable_character_templates_skills ADD CONSTRAINT FK_A9DE5E85585C142 FOREIGN KEY (skill_id) REFERENCES skill (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE skill ADD CONSTRAINT FK_5E3DE477DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE specie ADD CONSTRAINT FK_A280972DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE spell ADD CONSTRAINT FK_D03FCD8DDE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE talent ADD CONSTRAINT FK_16D902F5DE12AB56 FOREIGN KEY (created_by) REFERENCES "user" (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE talent_level ADD CONSTRAINT FK_6CBAD29418777CEF FOREIGN KEY (talent_id) REFERENCES talent (id) ON DELETE CASCADE NOT DEFERRABLE INITIALLY IMMEDIATE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE SCHEMA public');
        $this->addSql('ALTER TABLE being DROP CONSTRAINT FK_4686967CE48FD905');
        $this->addSql('ALTER TABLE being DROP CONSTRAINT FK_4686967CA76ED395');
        $this->addSql('ALTER TABLE being_spells DROP CONSTRAINT FK_11CAE50A186A5FCB');
        $this->addSql('ALTER TABLE being_spells DROP CONSTRAINT FK_11CAE50A479EC90D');
        $this->addSql('ALTER TABLE being_skills DROP CONSTRAINT FK_4C2CFC21186A5FCB');
        $this->addSql('ALTER TABLE being_skills DROP CONSTRAINT FK_4C2CFC215585C142');
        $this->addSql('ALTER TABLE being_items DROP CONSTRAINT FK_F5A5024E186A5FCB');
        $this->addSql('ALTER TABLE being_items DROP CONSTRAINT FK_F5A5024E126F525E');
        $this->addSql('ALTER TABLE playable_characters_kind DROP CONSTRAINT FK_94787C3C186A5FCB');
        $this->addSql('ALTER TABLE playable_characters_kind DROP CONSTRAINT FK_94787C3C30602CA9');
        $this->addSql('ALTER TABLE playable_characters_character_class DROP CONSTRAINT FK_E0683910186A5FCB');
        $this->addSql('ALTER TABLE playable_characters_character_class DROP CONSTRAINT FK_E0683910B201E281');
        $this->addSql('ALTER TABLE monsters_specie DROP CONSTRAINT FK_FFA328D7186A5FCB');
        $this->addSql('ALTER TABLE monsters_specie DROP CONSTRAINT FK_FFA328D7D5436AB7');
        $this->addSql('ALTER TABLE non_playable_characters_kind DROP CONSTRAINT FK_CA9E5A17186A5FCB');
        $this->addSql('ALTER TABLE non_playable_characters_kind DROP CONSTRAINT FK_CA9E5A1730602CA9');
        $this->addSql('ALTER TABLE non_playable_characters_character_class DROP CONSTRAINT FK_E165B81186A5FCB');
        $this->addSql('ALTER TABLE non_playable_characters_character_class DROP CONSTRAINT FK_E165B81B201E281');
        $this->addSql('ALTER TABLE being_talent DROP CONSTRAINT FK_8FC4E8A4186A5FCB');
        $this->addSql('ALTER TABLE being_talent DROP CONSTRAINT FK_8FC4E8A418777CEF');
        $this->addSql('ALTER TABLE character_class DROP CONSTRAINT FK_1388FEFDDE12AB56');
        $this->addSql('ALTER TABLE character_template DROP CONSTRAINT FK_CF61F612DE12AB56');
        $this->addSql('ALTER TABLE character_templates_kind DROP CONSTRAINT FK_CB4A2651B0A514');
        $this->addSql('ALTER TABLE character_templates_kind DROP CONSTRAINT FK_CB4A26530602CA9');
        $this->addSql('ALTER TABLE character_templates_character_class DROP CONSTRAINT FK_D53A531B0A514');
        $this->addSql('ALTER TABLE character_templates_character_class DROP CONSTRAINT FK_D53A53B201E281');
        $this->addSql('ALTER TABLE character_templates_spells DROP CONSTRAINT FK_3AA8E4FC1B0A514');
        $this->addSql('ALTER TABLE character_templates_spells DROP CONSTRAINT FK_3AA8E4FC479EC90D');
        $this->addSql('ALTER TABLE character_templates_skills DROP CONSTRAINT FK_674EFDD71B0A514');
        $this->addSql('ALTER TABLE character_templates_skills DROP CONSTRAINT FK_674EFDD75585C142');
        $this->addSql('ALTER TABLE character_templates_items DROP CONSTRAINT FK_23FE66F41B0A514');
        $this->addSql('ALTER TABLE character_templates_items DROP CONSTRAINT FK_23FE66F4126F525E');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583E48FD905');
        $this->addSql('ALTER TABLE equipment DROP CONSTRAINT FK_D338D583186A5FCB');
        $this->addSql('ALTER TABLE equipments_skills DROP CONSTRAINT FK_F4A04905517FE9FE');
        $this->addSql('ALTER TABLE equipments_skills DROP CONSTRAINT FK_F4A049055585C142');
        $this->addSql('ALTER TABLE equipments_spells DROP CONSTRAINT FK_A946502E517FE9FE');
        $this->addSql('ALTER TABLE equipments_spells DROP CONSTRAINT FK_A946502E479EC90D');
        $this->addSql('ALTER TABLE equipment_template DROP CONSTRAINT FK_A7A39BA5DE12AB56');
        $this->addSql('ALTER TABLE equipment_templates_skills DROP CONSTRAINT FK_A47E8C7F6498FB9F');
        $this->addSql('ALTER TABLE equipment_templates_skills DROP CONSTRAINT FK_A47E8C7F5585C142');
        $this->addSql('ALTER TABLE equipment_templates_spells DROP CONSTRAINT FK_F99895546498FB9F');
        $this->addSql('ALTER TABLE equipment_templates_spells DROP CONSTRAINT FK_F9989554479EC90D');
        $this->addSql('ALTER TABLE game DROP CONSTRAINT FK_232B318C503C0E1E');
        $this->addSql('ALTER TABLE item DROP CONSTRAINT FK_1F1B251EDE12AB56');
        $this->addSql('ALTER TABLE kind DROP CONSTRAINT FK_3BC4BCD9DE12AB56');
        $this->addSql('ALTER TABLE monster_template DROP CONSTRAINT FK_21A4530FDE12AB56');
        $this->addSql('ALTER TABLE monster_templates_specie DROP CONSTRAINT FK_9CBBCC5F2D30EB4A');
        $this->addSql('ALTER TABLE monster_templates_specie DROP CONSTRAINT FK_9CBBCC5FD5436AB7');
        $this->addSql('ALTER TABLE monster_templates_spells DROP CONSTRAINT FK_1E44CA762D30EB4A');
        $this->addSql('ALTER TABLE monster_templates_spells DROP CONSTRAINT FK_1E44CA76479EC90D');
        $this->addSql('ALTER TABLE monster_templates_items DROP CONSTRAINT FK_7B734A0771552540');
        $this->addSql('ALTER TABLE monster_templates_items DROP CONSTRAINT FK_7B734A07126F525E');
        $this->addSql('ALTER TABLE monster_templates_skills DROP CONSTRAINT FK_43A2D35D2D30EB4A');
        $this->addSql('ALTER TABLE monster_templates_skills DROP CONSTRAINT FK_43A2D35D5585C142');
        $this->addSql('ALTER TABLE non_playable_character_template DROP CONSTRAINT FK_9F46D872DE12AB56');
        $this->addSql('ALTER TABLE non_playable_character_templates_kind DROP CONSTRAINT FK_2BE8856DE76AD223');
        $this->addSql('ALTER TABLE non_playable_character_templates_kind DROP CONSTRAINT FK_2BE8856D30602CA9');
        $this->addSql('ALTER TABLE non_playable_character_templates_character_class DROP CONSTRAINT FK_70421A92E76AD223');
        $this->addSql('ALTER TABLE non_playable_character_templates_character_class DROP CONSTRAINT FK_70421A92B201E281');
        $this->addSql('ALTER TABLE non_playable_character_templates_spells DROP CONSTRAINT FK_577BFCC3E76AD223');
        $this->addSql('ALTER TABLE non_playable_character_templates_spells DROP CONSTRAINT FK_577BFCC3479EC90D');
        $this->addSql('ALTER TABLE non_playable_character_templates_items DROP CONSTRAINT FK_2D02B2E1E76AD223');
        $this->addSql('ALTER TABLE non_playable_character_templates_items DROP CONSTRAINT FK_2D02B2E1126F525E');
        $this->addSql('ALTER TABLE non_playable_character_templates_skills DROP CONSTRAINT FK_A9DE5E8E76AD223');
        $this->addSql('ALTER TABLE non_playable_character_templates_skills DROP CONSTRAINT FK_A9DE5E85585C142');
        $this->addSql('ALTER TABLE skill DROP CONSTRAINT FK_5E3DE477DE12AB56');
        $this->addSql('ALTER TABLE specie DROP CONSTRAINT FK_A280972DE12AB56');
        $this->addSql('ALTER TABLE spell DROP CONSTRAINT FK_D03FCD8DDE12AB56');
        $this->addSql('ALTER TABLE talent DROP CONSTRAINT FK_16D902F5DE12AB56');
        $this->addSql('ALTER TABLE talent_level DROP CONSTRAINT FK_6CBAD29418777CEF');
        $this->addSql('DROP TABLE "user"');
        $this->addSql('DROP TABLE being');
        $this->addSql('DROP TABLE being_spells');
        $this->addSql('DROP TABLE being_skills');
        $this->addSql('DROP TABLE being_items');
        $this->addSql('DROP TABLE playable_characters_kind');
        $this->addSql('DROP TABLE playable_characters_character_class');
        $this->addSql('DROP TABLE monsters_specie');
        $this->addSql('DROP TABLE non_playable_characters_kind');
        $this->addSql('DROP TABLE non_playable_characters_character_class');
        $this->addSql('DROP TABLE being_talent');
        $this->addSql('DROP TABLE character_class');
        $this->addSql('DROP TABLE character_template');
        $this->addSql('DROP TABLE character_templates_kind');
        $this->addSql('DROP TABLE character_templates_character_class');
        $this->addSql('DROP TABLE character_templates_spells');
        $this->addSql('DROP TABLE character_templates_skills');
        $this->addSql('DROP TABLE character_templates_items');
        $this->addSql('DROP TABLE equipment');
        $this->addSql('DROP TABLE equipments_skills');
        $this->addSql('DROP TABLE equipments_spells');
        $this->addSql('DROP TABLE equipment_template');
        $this->addSql('DROP TABLE equipment_templates_skills');
        $this->addSql('DROP TABLE equipment_templates_spells');
        $this->addSql('DROP TABLE game');
        $this->addSql('DROP TABLE item');
        $this->addSql('DROP TABLE kind');
        $this->addSql('DROP TABLE mastery');
        $this->addSql('DROP TABLE monster_template');
        $this->addSql('DROP TABLE monster_templates_specie');
        $this->addSql('DROP TABLE monster_templates_spells');
        $this->addSql('DROP TABLE monster_templates_items');
        $this->addSql('DROP TABLE monster_templates_skills');
        $this->addSql('DROP TABLE non_playable_character_template');
        $this->addSql('DROP TABLE non_playable_character_templates_kind');
        $this->addSql('DROP TABLE non_playable_character_templates_character_class');
        $this->addSql('DROP TABLE non_playable_character_templates_spells');
        $this->addSql('DROP TABLE non_playable_character_templates_items');
        $this->addSql('DROP TABLE non_playable_character_templates_skills');
        $this->addSql('DROP TABLE skill');
        $this->addSql('DROP TABLE specie');
        $this->addSql('DROP TABLE spell');
        $this->addSql('DROP TABLE talent');
        $this->addSql('DROP TABLE talent_level');
        $this->addSql('DROP TABLE messenger_messages');
    }
}
