name: Quality check
on: [push, pull_request]
jobs:
  quality:
    name: Quality Check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Codebase
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.5'
        tools: composer:v2

    - name: Validate composer files
      run: composer validate

    - name: Setup Cache
      run: echo "COMPOSER_CACHE_DIR=$(composer config cache-dir)" >> $GITHUB_ENV

    - name: Caching dependencies
      uses: actions/cache@v4
      id: cache
      with:
        path: ${{ env.COMPOSER_CACHE_DIR }}
        key: php8.5-composer-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          php8.5-composer-latest-

    - name: Update composer
      run: composer self-update

    - name: install dependencies
      run: composer install --prefer-dist --no-interaction --no-progress --optimize-autoloader --no-ansi

    - name: PHP Cs Fixer Check
      run: composer app:php-cs-fixer-check

    - name: PHPStan Analysis
      run: composer app:php-stan-analysis
